### ISSUE TITLE
feature: voice input support

### ISSUE THREAD

**Issue by jakobhoeg** [jakobhoeg/nextjs-ollama-llm-ui#17]
Add the ability to support voice input when prompting.

**Comment by MohammedZuhairAhmed** [comment]
Hi @jakobhoeg , This Feature has been done in my [PR](https://github.com/jakobhoeg/nextjs-ollama-llm-ui/pull/39), please Review it

**Comment by malteneuss** [comment]
Is this done with https://github.com/jakobhoeg/nextjs-ollama-llm-ui/pull/54 or should something like whisper be considered? (Probably overkill for now)
