### ISSUE TITLE
It would be great to turn off features - enforce only one default model

### ISSUE THREAD

**Issue by elearningshow** [jakobhoeg/nextjs-ollama-llm-ui#18]
Ability to turn off - Select Model, request edit in source code to just select a default model ()
Ability to turn off - Pull model to enforce use of only one particular model by all users

**Comment by jakobhoeg** [comment]
I need you to elaborate on this, as I don't see its purpose.

**Comment by elearningshow** [comment]
Please disregard thank you and keep up the good work.

**Comment by n00b21337** [comment]
I see this also as something I would like, to maybe just enforce one model and user cant choose which one. Maybe as some env variable value that can be set.
