### ISSUE TITLE
bug: pull model text parsing

### ISSUE THREAD

**Issue by Rushmore75** [jakobhoeg/nextjs-ollama-llm-ui#20]
It appears that the pull model field doesn't trim the input text. When I put in "dolphin-mixtral " it didn't find anything, but "dolphin-mixtral" did. I can fix this if I get time but it's probably faster for one the devs familiar with the project to find that part of the code

**Comment by jakobhoeg** [comment]
Thank you for pointing this out, I'll get it fixed! 🙏
