### ISSUE TITLE
Question: where chats logs are stored?

### ISSUE THREAD

**Issue by sogawa-sps** [jakobhoeg/nextjs-ollama-llm-ui#22]
Could you please advise where chat logs are stored, specifically on Windows?

**Comment by jakobhoeg** [comment]
They're stored in the browsers localstorage

**Comment by jakobhoeg** [comment]
> Could you please advise where chat logs are stored, specifically on Windows?

Hi!

Do you mean logs or chat history? For logs, please refer to the Ollama documentation.
Chats are stored in localstorage.
