### ISSUE TITLE
Feature: Add rendering for markdown

### ISSUE THREAD

**Issue by sogawa-sps** [jakobhoeg/nextjs-ollama-llm-ui#24]
Please consider adding rendering for markdown including tables.

**Comment by chanonroy** [comment]
We could achieve this with adding a package like [react-markdown](https://github.com/remarkjs/react-markdown).

It could be used on [this line](https://github.com/jakobhoeg/nextjs-ollama-llm-ui/blob/master/src/components/chat/chat-list.tsx#L122), like so:

```tsx
return <Markdown key={index}>{part}</Markdown>;
```

Example:
<img width="433" alt="Screenshot 2024-04-20 at 12 30 10 AM" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/16366896/40aafdfe-bf07-4691-bd2c-6380939155a0">

**Comment by sogawa-sps** [comment]
Looks good, thank you. Does it support tables?

**Comment by chanonroy** [comment]
Looks like there's a plugin called `remark-gfm` that allows us to support tables and other markdown [link](https://github.com/remarkjs/react-markdown?tab=readme-ov-file#use) 😄 

```tsx
import remarkGfm from 'remark-gfm'

<Markdown remarkPlugins={[remarkGfm]}>{markdown}</Markdown>
```

**Comment by jakobhoeg** [comment]
> Looks like there's a plugin called `remark-gfm` that allows us to support tables and other markdown [link](https://github.com/remarkjs/react-markdown?tab=readme-ov-file#use) 😄
> 
> ```tsx
> import remarkGfm from 'remark-gfm'
> 
> <Markdown remarkPlugins={[remarkGfm]}>{markdown}</Markdown>
> ```

Yup! Just added that also!
Thank you for the suggestion. I'll make sure to add you as a contributor to the PR.

**Comment by chanonroy** [comment]
Nice one. Looking forward to testing out the markdown 😄

**Comment by mattietea** [comment]
Markdown looks good! thanks for the suggestion @chanonroy
