### ISSUE TITLE
Can't fetch tags

### ISSUE THREAD

**Issue by mii9000** [jakobhoeg/nextjs-ollama-llm-ui#33]
![image](https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/6401874/3da0ceb8-ebcc-4596-bd38-a9ff35736b5e)
It fails here: https://github.com/jakobhoeg/nextjs-ollama-llm-ui/blob/master/src/app/api/tags/route.ts#L5-L7

**Comment by mii9000** [comment]
changing `NEXT_PUBLIC_OLLAMA_URL="http://localhost:11434"` to `NEXT_PUBLIC_OLLAMA_URL="http://127.0.0.1:11434"` fixed the issue.

**Comment by jakobhoeg** [comment]
Thanks for addressing your issue here @mii9000.

If you don't mind me asking, what OS are u running Ollama?

**Comment by mii9000** [comment]
MacOS
