### ISSUE TITLE
How do I run it like in the video demostration in the main page?

### ISSUE THREAD

**Issue by LoRAMilkshake** [jakobhoeg/nextjs-ollama-llm-ui#35]
In the README the first thing you're shown is a video demo of NextJS-Ollama running like a standalone app, but after installation I'm prompted to run it on localhost:3000 on my web browser; I'm using Fedora 36, 64bits. How can be used like it's shown in the README?

**Comment by jakobhoeg** [comment]
It’s a Next.js web frontend, not a desktop app. It’s meant to be run in the browser - as is also the case in the video preview.
