### ISSUE TITLE
Installation Issue: Specific Node Version Required?

### ISSUE THREAD

**Issue by tmattoneill** [jakobhoeg/nextjs-ollama-llm-ui#5]
Following the instructions on a system with:
`
ubuntu@ollama:~/nextjs-ollama-llm-ui$ node -v
>> v12.22.9
ubuntu@ollama:~/nextjs-ollama-llm-ui$ nvm -v
>> 0.39.3
ubuntu@ollama:~/nextjs-ollama-llm-ui$ npm -v
>>8.5.1
`

executing: npm install

throws about 50:
`
>> ubuntu@ollama:~/nextjs-ollama-llm-ui$ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package:
'@langchain/community@0.0.26',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@langchain/core@0.1.23',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
`

Is there a specific version of node to be using? Any one else run into this?

**Comment by tmattoneill** [comment]
Ah! Oddly when setting up a fresh box it used an ancient version of Node. I suggest anyone else having similar issues make sure you run "nvm install 21.6.1" after a fresh install to make sure you're current.

**Comment by jakobhoeg** [comment]
Thank you for reporting this issue.
Yeah, according to the [langchain docs](https://www.npmjs.com/package/langchain), it does indeed require node 18+.

Glad you got it working though 👍 

I'll update the readme to inform users about this.

**Comment by tmattoneill** [comment]
One other thing... now that I've got the server spinning up, when you access it, it launches "Compiliing", which runs for a bit and then crashes.

`
ubuntu@ollama:~/nextjs-ollama-llm-ui$ npm run dev

> nextjs-ollama-local-ai@0.1.0 dev
> next dev

   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Environments: .env

 ✓ Ready in 1710ms
 ○ Compiling / ...


ubuntu@ollama:~/nextjs-ollama-llm-ui$
`

Not sure what the issue is as no error is thrown but I'll keep tinkering.

Also, if you run the LATEST version of node (21) you get deprecation warnings. I went and installed 18 and I get no errors but I get a crash while "compiling" after pinging the server.

**Comment by jakobhoeg** [comment]
> One other thing... now that I've got the server spinning up, when you access it, it launches "Compiliing", which runs for a bit and then crashes.
> 
> ` ubuntu@ollama:~/nextjs-ollama-llm-ui$ npm run dev
> 
> > nextjs-ollama-local-ai@0.1.0 dev
> > next dev
> 
> ▲ Next.js 14.1.0
> 
> * Local:        http://localhost:3000
> * Environments: .env
> 
> ✓ Ready in 1710ms ○ Compiling / ...
> 
> ubuntu@ollama:~/nextjs-ollama-llm-ui$ `
> 
> Not sure what the issue is as no error is thrown but I'll keep tinkering.
> 
> Also, if you run the LATEST version of node (21) you get deprecation warnings. I went and installed 18 and I get no errors but I get a crash while "compiling" after pinging the server.

Can you create a new issue for this? 
And include the deprecation warnings. Thanks!
