### ISSUE TITLE
Question: Clickable links in the chat

### ISSUE THREAD

**Issue by sogawa-sps** [jakobhoeg/nextjs-ollama-llm-ui#68]
Hi,

Could you please advise if it’s possible to make links returned by an LLM clickable? The LLM can return them in any format, such as <a></a>, markdown, or any specific format that is needed. As for now none of them works.

Thank you.

**Comment by jakobhoeg** [comment]
They are clickable by default since they're rendered in markdown.


https://github.com/user-attachments/assets/061b5ef2-ad93-458f-ad0e-393573e28b84

**Comment by sogawa-sps** [comment]
Hi,

Sorry for the delay in responding. I realized that it didn't work because LLM was returning a URL with the space symbol, that's why it wasn't rendered. So, there are no generic issues here indeed, thank you.

However, I've got a new pretty specific problem :). Local links like this one `[test.txt](file:///c:/temp/test.txt)` don't work. They point to the localhost instead.
