### ISSUE TITLE
Version Requirements: 18.17+

### ISSUE THREAD

**Issue by tmattoneill** [jakobhoeg/nextjs-ollama-llm-ui#7]
Just a quick note that you must use 18.17+ for the code to work. Using 18.9 for example, fails.

`You are using Node.js 18.9.1. For Next.js, Node.js version >= v18.17.0 is required.`

**Comment by tmattoneill** [comment]
One other note: if you are running v. 21+ you get a deprecation warning:
`(node:3423) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)`

**Comment by jakobhoeg** [comment]
Newest version of NextJS does indeed require Node 18.17+.

As to why the deprecation warning shows when running 21+, I don't think it is a specific issue with this repository, but rather a general issue: [depcreation warning](https://github.com/yarnpkg/yarn/issues/9013)

With that being said, I am closing this issue.
