### ISSUE TITLE
No model availables

### ISSUE THREAD

**Issue by nejib1** [jakobhoeg/nextjs-ollama-llm-ui#9]
Hello, 

I can pull models, but nextjs-ollama-llm-ui can't detect anyone.
Ollama and ollama-webui can detect models but not nextjs-ollama-llm-ui, could you please fix it ?

![image](https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/10485460/84abb57c-6765-46fd-8e6a-b4090b30b663)

**Comment by jakobhoeg** [comment]
There is already an open issue addressing this issue, so I am closing this one.
